### ISSUE TITLE
[BUG]日历解析错误

### ISSUE THREAD

**Issue by 1109039773** [CodeCraftersCN/JDevKit#16]
**Which module creates this bug**
- [ ] `devkit-core`
- [ ] `devkit-utils`
- [ ] `guid`
- [x] `webcal`
- [ ] `simple-jwt-facade`
- [ ] `simple-jwt-authzero`
- [ ] `simple-jwt-jjwt`
- [ ] `simple-jwt-spring-boot-starter`

**Describe the bug**

使用Springboot生成ics文件后，只有windows 10的日历软件能够识别，其他的均无法解析ics文件，并添加日历事件

![bug](https://github.com/CodeCraftersCN/JDevKit/assets/74454731/14805242-d365-4d23-bf0f-9f6b3dcd979b)

**To Reproduce**

springboot endpoint:

```java
    @GetMapping(value = "/camp", produces = "text/calendar")
    public ResponseEntity<String> campEvent(){
        return ResponseEntity.ok(new WebCalendar()
                .setCompanyName("小学生夏令营公司")
                .setName("小学生夏令营一号")
                .setDomainName("xxscamp.com")
                .setProductName("小学生水上乐园")
                .addEvent(new WebCalendarEvent()
                        .setClassification(Classification.PUBLIC)
                        .setDescription("玩水")
                        .setStart(LocalDateTime.of(2023,9,21,15,0,0))
                        .setDuration(Duration.ofHours(2))
                        .setSummary("玩水")
                        .setLocation("世界之窗")).resolve());
    }
```

生成的ics文件如下
```text
BEGIN:VCALENDAR
PRODID:-//小学生夏令营公司//小学生水上乐园//EN
VERSION:2.0
X-WR-CALNAME:小学生夏令营一号

BEGIN:VEVENT
UID:[36245486-5090-4346-934f-a5f2c1e5c03f@xxscamp.com](mailto:36245486-5090-4346-934f-a5f2c1e5c03f@xxscamp.com)
SUMMARY:玩水
DTSTART;TZID=Asia/Shanghai:2023-09-21T15:00:00
DURATION:PT7200S
CLASS:PUBLIC
DESCRIPTION:玩水
LOCATION:世界之窗
END:VEVENT

END:VCALENDAR
```

**Developing Environment:**
 - OS: Windows
 - Version 1.1.0
 - Java Version: Amazon Corretto 17

**Comment by zihluwang** [comment]
已修复，将在明日发布**1.1.1**版本进行修复。

经过验证，使用原文中的代码在更新后的输出为：
```text
BEGIN:VCALENDAR
PRODID:-//小学生夏令营公司//小学生水上乐园//EN
VERSION:2.0
X-WR-CALNAME:小学生夏令营一号
BEGIN:VEVENT
UID:b03ffe97-8ddf-434b-a2d5-cc0bf4edda61@xxscamp.com
DTSTAMP:20230922T013009Z
DTSTART:20230921T070000Z
DURATION:PT7200S

SUMMARY:玩水
CLASS:PUBLIC

LOCATION:世界之窗
DESCRIPTION:玩水
END:VEVENT
END:VCALENDAR
```

在 [iCalendar.org 的在线验证](https://icalendar.org/validator.html)中验证的结果：
<img width="853" alt="image" src="https://github.com/CodeCraftersCN/JDevKit/assets/47817169/a2ff8b8d-9410-4420-a51e-44d3f58752b6">

导入到 macOS 中的 Calendar.app 的结果为：
<img width="971" alt="image" src="https://github.com/CodeCraftersCN/JDevKit/assets/47817169/2a5ed8da-8848-4704-afb5-4d8bcc939838">
